[package]
name    = "lpc82x"
version = "0.6.0"
authors = ["Hanno Braun <hanno@braun-robotics.com>"]
edition = "2018"

description = "DEPRECATED. Use lpc82x-hal or lpc82x-pac instead."
license     = "0BSD"
readme      = "README.md"
